# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('existence', models.CharField(db_column='Protein Existence', max_length=255)),
                ('lrrce_seq', models.CharField(db_column='LRRCE sequence', max_length=255)),
                ('uniprot_seq', models.TextField(blank=True)),
                ('ncbi_seq', models.TextField(blank=True)),
                ('genbank_seq', models.TextField(blank=True)),
                ('class_field', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('link_title', models.CharField(max_length=50)),
                ('primary', models.BooleanField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Organism'),
        ),
        migrations.AddField(
            model_name='gene',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Organism'),
        ),
    ]
