# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170422_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='ensembl_seq',
            field=models.TextField(blank=True),
        ),
    ]
