# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gene_ensembl_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='lrrce_seq',
            field=models.CharField(blank=True, db_column='LRRCE sequence', max_length=255),
        ),
    ]
