# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170424_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='lrrce_seq',
            field=models.CharField(db_column='LRRCE sequence', max_length=255),
        ),
    ]
